name: Deploying Process

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    name: Deploying the code to server
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Copy files to root directory
      run: cp -rf ./ /var/www/kazumischool/

      
    
